server:
  port: 8080
  ssl:
    key-store: mykeys.jks
    key-store-password: letmein
    key-password: letmein

spring:
  datasource:
    url: jdbc:h2:mem:test
  application:
    name: Spring Demo

logging:
  level:
    root: info
  file.name: /home/erick/demoApp.log

application:
  welcome: Welcome to ${spring.application.name}!

